config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  resources :forums
  root 'posts#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users, only: [:edit, :update]
  resources :tags

  resources :posts do 
  member do
    put "like", to: "posts#upvote"
    put "dislike", to: "posts#downvote"
  end
end

resources :forums do 
  member do
    put "like", to: "forums#upvote"
    put "dislike", to: "forums#downvote"
  end
end

resources :forums do 
  resources :comments
end

end

app/models/forum.rb
class Forum < ApplicationRecord
	has_many :taggings 
	has_many :tags, through: :taggings 
	belongs_to :user
	acts_as_votable
  has_many :comments, dependent: :destroy

	# for fiendly-id
	extend FriendlyId
	friendly_id :title, use: :slugged

	# for search
	def self.search(search)
		where("title LIKE ?", "%#{search}%")
	end

	# for prev and next button
 	def next
    	self.class.where("id > ?", id).first
  	end
  	def previous
    	self.class.where("id < ?", id).last
  	end

	# for tags
  	def tag_list
  		self.tags.collect do |tag|
    		tag.name
  		end.join(", ")
	end

	def tag_list=(tags_string)
  		tag_names = tags_string.split(",").collect{|s| s.strip.capitalize}.uniq
  		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  		tag_names.each do |tag|
  			@tag = Tag.find_by(name: tag)
  			@tag.forums_count += 1
  			@tag.save!
  		end
  		self.tags = new_or_found_tags
	end

end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

	before_action :find_forum, only: [:show, :edit, :update, :destroy]

	def index
		if params[:search]
    		@forums = Forum.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 4)
  		else
    		@forums = Forum.all.order('created_at DESC').paginate(page: params[:page], per_page: 4)
  		end
	end

	def new
		@forum = Forum.new
	end

	def create
		@forum = Forum.new forum_params
		@forum.user_id = current_user.id
		if @forum.save
			redirect_to @forum, notice: "Forum created"
		else
			render 'new', notice: "unable to save"
		end
	end

	def show
		@forum = Forum.friendly.find(params[:id])

		@prev_forum = @forum.previous
		@next_forum = @forum.next
	end

	def edit
	end

	def update
		if @forum.update forum_params
			redirect_to @forum, notice: "Forum successfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@forum.tags.each do |tag|
			tag.forums_count -= 1;
			tag.save!
		end
		@forum.destroy
		redirect_to forums_path
	end

	def upvote 
  		@forum = Forum.friendly.find(params[:id])
  		if @forum.upvote_by current_user
  			@forum.cached_votes_up += 1
  		end
  		redirect_to :back
	end

	def downvote 
  		@forum = Forum.friendly.find(params[:id])
  		if @forum.downvote_by current_user
  			@forum.cached_votes_up -= 1
  		end
  		redirect_to :back
	end

	private

	def forum_params
		params.require(:forum).permit(:title, :content, :slug, :tag_ids => [])
	end

	def find_forum
		@forum = Forum.friendly.find(params[:id])
	end


end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= simple_form_for @forum do |f| %>
	<% if @forum.errors.any? %>
		<h2><%= pluralize(@forum.errors.count, "error") %> prevented this forum from saving:</h2>
		<ul>
			<% @forum.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<p>
	<%= f.label :content, "Title of the Question:" %><br>
	<%= f.text_field :title %>
	</p>

	<p>
	<%= f.label :content, "Explaination of the Question:" %><br>
	<%= f.cktext_area :content %>
	</p>

	<p>
  		<%= f.association :tags, label: false%>
	</p>

	<%= f.submit %>

<% end %>

<script>
$(document).ready(function() {
        $("#forum_tag_ids").select2({
        	placeholder: "Select Tags",
        	maximumSelectionLength: 3,
        	tokenSeparators: [',', ' ']
        })
    });

</script>

app/views/forums/edit.html.erb
<div class="row">
<div class="col-md-10 col-md-offset-1">
<h3 align = "center">Update This Forum</h3>
<p align = "center">
 <%= link_to "All Forums", forums_path , class: 'btn btn-default btn-sm' %>
</p>
<%= render 'form' %>


 </div>
 </div>

app/views/forums/index.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-2">
		<%= form_tag(forums_path, :method => "get", id: "search-form") do %>
		<%= text_field_tag :search, params[:search], placeholder: "Search Forums" %>
		<%= submit_tag "Search" %>
		<% end %>
	</div>
	<div class="col-md-3 col-md-offset-1">
		<p align="right"> <%= link_to "New Forum", new_forum_path %> </p>
	</div>
</div>
<hr>

<div class="row">
  <div class="col-md-6 col-md-offset-1">
  <h3>Recent Forums</h3>
  	<% @forums.each do |forum| %>
			<h3><%= link_to forum.title, forum %></h3>
			<p class="date">asked <%= forum.created_at.strftime("%b %d '%y at %H:%M") %></p>
			<p><%= forum.get_upvotes.size %> upvotes &nbsp; &nbsp; &nbsp;<%= forum.comments.count %> answers</p>
      <hr>
	<% end %>

	<%= will_paginate @forums %>
  </div>
  <div class="col-md-4 ">
  	<h3>Most Upvoted forums</h3>
  		<% Forum.order('cached_votes_up DESC').each do |forum|%>
  			<h4><%= link_to forum.title, forum %> <span class="badge"><%= forum.cached_votes_up%></span><h4>
  		<% end %>
  		<hr>
  	<h3>Tags</h3>
  	<% Tag.order('name DESC').each do |tag|%>
    <% if tag.forums.count > 0 %>
  		<h4><%= link_to tag.name, tag_path(tag) %> <span class="badge"><%= tag.forums.count %></span></h4>
      <% end %>
  	<% end %>
  </div>
</div>

app/views/forums/new.html.erb
<div class="row">
<div class="col-md-10 col-md-offset-1">
<h3 align = "center">New Forum</h3>
<p align = "center">
 <%= link_to "All Forums", forums_path , class: 'btn btn-default btn-sm' %>
</p>
<%= render 'form' %>


 </div>
 </div>

app/views/forums/show.html.erb
<div class="row">
<div class="col-md-2">

<nav aria-label="...">
  <ul class="pager">
    <li>
      <%if @prev_forum!=nil %>
      <%= link_to  'Previous', @prev_forum %><p>
    <% end %>
  </li>
  </ul>
  </nav>
  </div>


  <div class="col-md-8 ">

  <h2 align><%= @forum.title %></h2><hr>



<h4><br>
<%= @forum.content.html_safe %><br>
</h4>
<% @forum.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag), class: 'btn btn-default btn-sm' %>
  <% end %>

<p align="right">asked <%= @forum.created_at.strftime("%b %d '%y at %H:%M") %></p>
    <p align="right"><%= image_tag(User.find(@forum.user_id).avatar, size: '50x50') %> <strong><%= User.find(@forum.user_id).name %></strong></p>

  

<p align = "center">
<%=link_to like_forum_path(@forum), method: :put, class: 'btn btn-default btn-sm' do %>
 <span class="glyphicon glyphicon-thumbs-up"></span><%=@forum.get_upvotes.size%></td>
 <% end %>
 <%=link_to dislike_forum_path(@forum), method: :put, class: 'btn btn-default btn-sm' do %>
 <span class="glyphicon glyphicon-thumbs-down"> </span><%=@forum.get_downvotes.size%></td>
 <% end %>

 <% if can? :manage, @forum %>
<%= link_to "Edit Forum", edit_forum_path(@forum), class: 'btn btn-default btn-sm' %>
<%= link_to "Delete Forum", forum_path(@forum), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-default btn-sm'  %>
<% end %>

<%= link_to "All Forums", forums_path , class: 'btn btn-default btn-sm' %>
</p>

<div id="comments">
<hr>
    <h4 align="center"><%= @forum.comments.count %> Answers</h4><hr>
    <%= render @forum.comments %>

    <h4>Your Answer</h4>
    <%= render "comments/form" %>
  </div>

</div>

<div class="col-md-2">

<nav aria-label="...">
  <ul class="pager">
   <li>
      <%if @next_forum!=nil %>
      <%= link_to  'Next', @next_forum %></p><br>
    <% end %>

    </li>
  </ul>
  </nav>
  </div>
</div>