config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  resources :forums
  root 'posts#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users, only: [:edit, :update]
  resources :tags

  resources :posts do 
  member do
    put "like", to: "posts#upvote"
    put "dislike", to: "posts#downvote"
  end
end

resources :forums do 
  member do
    put "like", to: "forums#upvote"
    put "dislike", to: "forums#downvote"
  end
end

resources :forums do 
  resources :comments
end

end

app/models/post.rb
class Post < ApplicationRecord
	has_many :taggings 
	has_many :tags, through: :taggings 
	belongs_to :user
	acts_as_votable

	# for friendly-id
	extend FriendlyId
	friendly_id :title, use: :slugged


	def self.search(search)
		where("title LIKE ?", "%#{search}%")
	end

	# for prev and next button
 	def next
    	self.class.where("id > ?", id).first
  	end
  	def previous
    	self.class.where("id < ?", id).last
  	end

  	# for tags
  	def tag_list
  		self.tags.collect do |tag|
    		tag.name
  		end.join(", ")
	end

	def tag_list=(tags_string)
  		tag_names = tags_string.split(",").collect{|s| s.strip.capitalize}.uniq
  		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  		tag_names.each do |tag|
  			@tag = Tag.find_by(name: tag)
  			@tag.posts_count += 1
  			@tag.save!
  		end
  		self.tags = new_or_found_tags
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		if params[:search]
    		@posts = Post.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 4)
  		else
    		@posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 4)
  		end
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params
		@post.user_id = current_user.id
		if @post.save
			redirect_to @post, notice: "Post created"
		else
			render 'new', notice: "unable to save"
		end
	end

	def show
		@post = Post.friendly.find(params[:id])

		@prev_post = @post.previous
		@next_post = @post.next
	end

	def edit
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "Post successfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@post.tags.each do |tag|
			tag.posts_count -= 1;
			tag.save!
		end
		@post.destroy
		redirect_to posts_path
	end

	def upvote 
  		@post = Post.friendly.find(params[:id])
  		if @post.upvote_by current_user
  			@post.cached_votes_up += 1
  		end
  		redirect_to :back
	end

	def downvote 
  		@post = Post.friendly.find(params[:id])
  		if @post.downvote_by current_user
  			@post.cached_votes_up -= 1
  		end
  		redirect_to :back
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :slug, :tag_list)
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = '//recursion-blogging.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
	</p>

	<p>
	<%= f.label :content, "Write your article here" %><br>
	<%= f.cktext_area :content %>
	</p>

	<p>
  		<%= f.label :Tags %><br />
  		<%= f.text_field :tag_list %>
	</p>

	<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<div class="row">
<div class="col-md-10 col-md-offset-1">
<h3 align = "center">Update This Post</h3>
<p align = "center">
 <%= link_to "All Posts", posts_path , class: 'btn btn-default btn-sm' %>
</p>
<%= render 'form' %>


 </div>
 </div>

app/views/posts/index.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-2">
		<%= form_tag(posts_path, :method => "get", id: "search-form") do %>
		<%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
		<%= submit_tag "Search" %>
		<% end %>
	</div>
  <%# if can? :manage, @post %>
	<div class="col-md-3 col-md-offset-1">
		<p align="right"> <%= link_to "New Blog", new_post_path %> </p>
	</div>
  <%# end %>
  
</div>
<hr>

<div class="row">
  <div class="col-md-6 col-md-offset-1">
  <h3>Recent Blogs</h3>
    <% @posts.each do |post| %>
      <h3><%= link_to post.title, post %></h3>
      <p class="date">asked <%= post.created_at.strftime("%b %d '%y at %H:%M") %></p>
      <p><%= post.get_upvotes.size %> upvotes </p>
      <hr>
  <% end %>

	<%= will_paginate @posts %>
  </div>
  <div class="col-md-4 ">
  	<h3>Most Upvoted Posts</h3>
  		<% Post.order('cached_votes_up DESC').each do |post|%>
  			<h4><%= link_to post.title, post %> <span class="badge"><%= post.cached_votes_up%></span><h4>
  		<% end %>
  		<hr>
  	<h3>Tags</h3>
    <% Tag.order('name DESC').each do |tag|%>
    <% if tag.posts.count > 0 %>
      <h4><%= link_to tag.name, tag_path(tag) %> <span class="badge"><%= tag.posts.count %></span></h4>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
<div class="col-md-10 col-md-offset-1">
<h3 align = "center">New Post</h3>
<p align = "center">
 <%= link_to "All Posts", posts_path , class: 'btn btn-default btn-sm' %>
</p>
<%= render 'form' %>


 </div>
 </div>

app/views/posts/show.html.erb
<div class="row">
<div class="col-md-2">

<nav aria-label="...">
  <ul class="pager">
    <li>
      <%if @prev_post!=nil %>
      <%= link_to  'Previous', @prev_post %><p>
    <% end %>
  </li>
  </ul>
  </nav>
  </div>


  <div class="col-md-8 ">

  <h2 align = "center"><%= @post.title %></h2>

<h4><br>
<%= @post.content.html_safe %><br>
</h4>
<% @post.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag), class: 'btn btn-default btn-sm' %>
  <% end %>

<p align="right">Posted <%= @post.created_at.strftime("%b %d '%y at %H:%M") %></p>
    <p align="right"><%= image_tag(User.find(@post.user_id).avatar, size: '50x50') %> <strong><%= User.find(@post.user_id).name %></strong></p>
<br>
<p align = "center">
<%=link_to like_post_path(@post), method: :put, class: 'btn btn-default btn-sm' do %>
 <span class="glyphicon glyphicon-thumbs-up"></span><%=@post.get_upvotes.size%></td>
 <% end %>
 <%=link_to dislike_post_path(@post), method: :put, class: 'btn btn-default btn-sm' do %>
 <span class="glyphicon glyphicon-thumbs-down"></span><%=@post.get_downvotes.size%></td>
 <% end %>
 
<%= link_to "Edit Article", edit_post_path(@post), class: 'btn btn-default btn-sm' %>
<%= link_to "Delete Article", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-default btn-sm'  %>
<%= link_to "All Articles", posts_path , class: 'btn btn-default btn-sm' %>
</p>
<br><hr><br>
<%= render 'disqus' %>

</div>

<div class="col-md-2">

<nav aria-label="...">
  <ul class="pager">
   <li>
      <%if @next_post!=nil %>
      <%= link_to  'Next', @next_post %></p><br>
    <% end %>

    </li>
  </ul>
  </nav>
  </div>
</div>